Backend unit tests
SEP-TU-e-2024/website pull request #148
Opened 2024-06-10 12:52 UTC by rijkman

## Honey, the backend unit tests are here!

To run the tests:
* `cd backend`
* `python manage.py test tests`
To check coverage, you will have to install it first.
* `pip install coverage`
* `cd backend`
* `coverage run --source='.' manage.py test tests `
* `coverage report --include api\views\*,tests\*,api\models.py,api\serializers.py,api\data_processing\*` for a brief report in the CLI
* `coverage html --include api\views\*,tests\*,api\models.py,api\serializers.py,api\data_processing\*`  if you want a fancy html output (to be found in backend/htmlcov)

## Coverage Progress
| Name                                              | Stmts | Miss | Cover |
|---------------------------------------------------|-------|------|-------|
| api\data_processing\leaderboard.py                |    19 |    0 | 100%  |
| api\data_processing\leaderboard_entry.py          |    16 |    0 | 100%  |
| api\models.py                                     |    90 |    0 | 100%  |
| api\serializers.py                                |    46 |    0 | 100%  |
| api\views\auth_view.py                            |    86 |    5 |  94%  |
| api\views\leaderboard_entry_view.py               |    13 |    1 |  92%  |
| api\views\leaderboard_view.py                     |    13 |    1 |  92%  |
| api\views\problem_occurence_view.py               |    16 |    1 |  94%  |
| api\views\problem_view.py                         |    12 |    1 |  92%  |
| api\views\result_view.py                          |    13 |    1 |  92%  |
| api\views\submit_view.py                          |    95 |   51 |  46%  |
| api\views\views.py                                |     9 |    1 |  89%  |
| tests\__init__.py                                 |     0 |    0 | 100%  |
| tests\test_auth_view.py                           |    61 |   19 |  69%  |
| tests\test_confirm_submission.py                  |    25 |    0 | 100%  |
| tests\test_evaluation_settings.py                 |    11 |    0 | 100%  |
| tests\test_leaderboard_entry_view.py              |    22 |    0 | 100%  |
| tests\test_leaderboard_view.py                    |    24 |    0 | 100%  |
| tests\test_problem_occurrence__overview_view.py   |    24 |    0 | 100%  |
| tests\test_problem_occurrence_view.py             |    18 |    0 | 100%  |
| tests\test_result_view.py                         |    15 |    0 | 100%  |
| tests\test_user_profile_manager.py                |    21 |    0 | 100%  |
| **TOTAL**                                         | **649** | **81** | **88%** |

## TODO:
- I don't know how to mock a blob storage, but i'm pretty sure it's not really possible either. We'll have to find some other alternative.
- Metric tests have not been implemented because their schema is not known (as of now)

2024-06-11 20:45 UTC, marnikdenouden commented on backend/api/models.py
>      benchmark_instance = models.ForeignKey(BenchmarkInstance, on_delete=models.CASCADE, null=True)
It seems like benchmark_instance is now twice in the result model?

2024-06-12 07:12 UTC, Doodshoofdaapje requested changes
I think its a very good start to the unit test, but i also feel like some changes will break the current main. In particulair the changing of error messages will probably break frontend error displays. Comments about optional test cases are technically not required for this task, but might be nice to add still. I have not tested your code, i will do that after some changes are made.

2024-06-12 07:12 UTC, Doodshoofdaapje commented on backend/tests/test_auth_view.py
> +
Should there be a test for email already in use?

2024-06-12 07:12 UTC, Doodshoofdaapje commented on backend/tests/test_auth_view.py
> +        req.data = {
Isnt this already in the request

2024-06-12 07:12 UTC, Doodshoofdaapje commented on backend/tests/test_auth_view.py
> +        req.data = {
Isnt this already in the request?

2024-06-12 07:12 UTC, Doodshoofdaapje commented on backend/tests/test_auth_view.py
> +
I believe it may also fail if user is already activated (might be wrong on this on)

2024-06-12 07:12 UTC, Doodshoofdaapje commented on backend/tests/test_leaderboard_entry_view.py
> +
Why not test bad cases?

2024-06-12 07:12 UTC, Doodshoofdaapje commented on backend/tests/test_leaderboard_view.py
> +
Shouldnt we test bad cases as well?

2024-06-12 07:12 UTC, Doodshoofdaapje commented on backend/tests/test_leaderboard_entry_view.py
> +
What about checking if the aggregates are correct?

2024-06-12 07:12 UTC, Doodshoofdaapje commented on backend/tests/test_user_profile_manager.py
> +
What about email already in use?

2024-06-12 07:12 UTC, Doodshoofdaapje commented on frontend/src/components/homepage/HomePage.jsx
> +
Controversial change if i do say so myself

2024-06-12 07:14 UTC, Doodshoofdaapje commented
Btw the code quality complains about result_view.py not having comments (It has division by zero error if there is not code and only comments) 
![image](https://github.com/SEP-TU-e-2024/website/assets/97123208/023d8ecb-ee19-4679-adcc-e291f7761035)

2024-06-12 11:10 UTC, rijkman commented on backend/api/models.py
>      benchmark_instance = models.ForeignKey(BenchmarkInstance, on_delete=models.CASCADE, null=True)
removed

2024-06-12 11:11 UTC, rijkman commented on backend/api/models.py
> +    benchmark_instance = models.ForeignKey(BenchmarkInstance, on_delete=models.CASCADE)
removed

2024-06-12 11:11 UTC, rijkman commented on backend/api/urls.py
> +# from .views.result_view import ResultView
removed

2024-06-12 14:00 UTC, rijkman commented on backend/api/views/auth_view.py
> +                "User error: User not found", status=status.HTTP_404_NOT_FOUND
reverted

2024-06-12 14:00 UTC, rijkman commented on backend/tests/test_auth_view.py
> +
updated error message

2024-06-12 14:01 UTC, rijkman commented on backend/tests/test_leaderboard_entry_view.py
> +
1. What do you mean with 'bad cases'?   2. Isn't data aggregated in the frontend?

2024-06-12 14:02 UTC, rijkman commented on backend/tests/test_leaderboard_view.py
> +
What do you mean with bad cases

2024-06-12 14:04 UTC, rijkman commented on backend/api/views/auth_view.py
> +                "Email error: Failed to send email",
reverted

2024-06-12 14:04 UTC, rijkman commented on backend/api/views/auth_view.py
> +                "User error: User not found", status=status.HTTP_400_BAD_REQUEST
reverted

2024-06-12 14:04 UTC, rijkman commented on backend/api/views/auth_view.py
> +            "User error: Invalid Token", status=status.HTTP_400_BAD_REQUEST
reverted

2024-06-12 14:05 UTC, rijkman commented on backend/api/views/result_view.py
> +# from django.http import JsonResponse
sure

2024-06-12 14:09 UTC, rijkman commented on backend/tests/test_auth_view.py
> +        req.data = {
removed second assignment

2024-06-12 14:09 UTC, rijkman commented on backend/tests/test_auth_view.py
> +        req.data = {
removed second assignment

2024-06-12 14:10 UTC, rijkman commented on backend/tests/test_auth_view.py
> +
only if there is a separate error for that IMO. the unit tests just test that all the possible code paths are tested

2024-06-13 07:41 UTC, Doodshoofdaapje commented on backend/tests/test_leaderboard_view.py
> +
What if problem doesnt exists? It throws errors for this but its not tested

2024-06-13 07:43 UTC, Doodshoofdaapje commented on backend/tests/test_user_profile_manager.py
> +
There is actually, just not explicit in the code
![image](https://github.com/SEP-TU-e-2024/website/assets/97123208/169b6444-e1c1-45c3-9570-b7b733f79a77)
This piece of code automaticly checks for unique constraints on users (Try logging in with an invalid email and you get an error for this, same for regristation for email already in use)

2024-06-13 13:26 UTC, Doodshoofdaapje approved these changes
God zij met u tot ons wederzien

2024-06-13 13:27 UTC, merged