Update leaderboard instances
SEP-TU-e-2024/website pull request #149
Opened 2024-06-11 10:20 UTC by marnikdenouden

# Leaderboard sub table
Connect the leaderboard instance table to dynamic data. For this I updated the leaderboard data processing to create a more solid data bundle that can be used by the front end, but also to make the code more structured.

2024-06-11 12:53 UTC, Doodshoofdaapje requested changes
Fix on click listeners and aggregation

2024-06-11 12:53 UTC, Doodshoofdaapje commented on frontend/src/components/leaderboards/Leaderboard.jsx
> +    (entry) => { return <div className="download-cell"><i onClick={getDownloadSingleSolutionOnClickHandler(submission, entry)} role="button" className="bi-download"/></div> },
You can not pass paramters to an onclick listener like this. It needs a reference to a method, currently you are calling the function. Therefore the button does not do anything.

2024-06-11 12:53 UTC, Doodshoofdaapje commented on frontend/src/components/leaderboards/Leaderboard.jsx
> +    (entry) => { return <div className="download-cell"><i onClick={getHandleVisualizePiOnClickHandler(submission, entry)} role="button" className="bi-eye"/></div> },
You can not pass paramters to an onclick listener like this. It needs a reference to a method, currently you are calling the function. Therefore the button does not do anything.

2024-06-11 12:53 UTC, Doodshoofdaapje commented on backend/api/data_processing/leaderboard_entry.py
> +            self.results[metric.name] = sum(scores) / len(scores)
Something goes wrong here, aggregates seem very random

2024-06-11 18:11 UTC, marnikdenouden commented on frontend/src/components/leaderboards/Leaderboard.jsx
> +    (entry) => { return <div className="download-cell"><i onClick={getDownloadSingleSolutionOnClickHandler(submission, entry)} role="button" className="bi-download"/></div> },
In fact it does work, as I have tested it. It is not the method itself that is the function for the onclick, but rather a function that creates the on click listener using the submission and entry.

2024-06-11 18:12 UTC, marnikdenouden commented on frontend/src/components/leaderboards/Leaderboard.jsx
> +    (entry) => { return <div className="download-cell"><i onClick={getHandleVisualizePiOnClickHandler(submission, entry)} role="button" className="bi-eye"/></div> },
Same story as for the other getOnClickHandler

2024-06-11 18:36 UTC, marnikdenouden commented on frontend/src/components/leaderboards/Leaderboard.jsx
> +    (entry) => { return <div className="download-cell"><i onClick={getHandleVisualizePiOnClickHandler(submission, entry)} role="button" className="bi-eye"/></div> },
Same story for the function that the getOnClickHandler returns, event != e.

2024-06-11 18:37 UTC, marnikdenouden commented on frontend/src/components/leaderboards/Leaderboard.jsx
> +    (entry) => { return <div className="download-cell"><i onClick={getDownloadSingleSolutionOnClickHandler(submission, entry)} role="button" className="bi-download"/></div> },
Thanks for noting, the button functionality was in fact broken, but not due to this. The method getDownloadSingleSolutionOnClickHandler is not the method that runs on click, but as the name suggests gets the on click handler function. What was broken and is not fixed in a new commit is that the on click handler has the parameter named 'event' and used the reference 'e'.

2024-06-12 07:55 UTC, Doodshoofdaapje approved these changes
goode

2024-06-12 07:58 UTC, merged