Benchmark instance names
SEP-TU-e-2024/website pull request #193
Opened 2024-06-21 09:50 UTC by marnikdenouden

Add name field to benchmark instance data model
Remove option for some fields to be null-able, such as evaluation settings.
Update benchmark instance serializer
Utilize benchmark instance name in front end display

2024-06-24 17:45 UTC, ThijsEgberts requested changes
I haven't been able to test everything because the fixture isn't in line with the current database schema but besides that I think there might be some problems with how emails are done for anon submissions now so that should be tested more

2024-06-24 17:45 UTC, ThijsEgberts commented on backend/api/fixtures/0004_instance_names.json
> +        "container": null,
container can't be null

2024-06-24 17:45 UTC, ThijsEgberts commented on backend/api/fixtures/0004_instance_names.json
> +        "container": null,
container can't be null

2024-06-24 17:45 UTC, ThijsEgberts commented on backend/api/fixtures/0004_instance_names.json
> +        "container": null,
container can't be null

2024-06-24 17:45 UTC, ThijsEgberts commented on backend/api/fixtures/0004_instance_names.json
> +        "container": null,
container is non-nullable

2024-06-24 17:45 UTC, ThijsEgberts commented on backend/api/fixtures/0004_instance_names.json
I marked them as individual comments but there are a bunch of submissions in the fixture that don't have a container associated

2024-06-24 17:45 UTC, ThijsEgberts commented on frontend/src/components/submit/Submit.jsx
> +      e.target.email ? formData.append('email', e.target.email.value) : undefined;
This seems like a bad idea since in the submission view there is no proper error handling for an undefined email and the email field is not requirered for anonymous submission in the frontend.
In the backend anounymous submissions are made by creating or attaching a user account on the fly so if the submission doesn't have an attached email or account I think it should give errors somewhere

2024-06-28 09:28 UTC, Doodshoofdaapje approved these changes
Bazinga

2024-06-28 09:31 UTC, merged