Problem occurrence unit tests
SEP-TU-e-2024/website pull request #222
Opened 2024-06-26 10:19 UTC by Doodshoofdaapje

Introduces 100% coverage unit tests for all the problem occurrence overview pages

2024-06-26 16:07 UTC, Booksh commented on frontend/src/components/problemOccurenceOverview/ProblemOccurrenceOverviewPage.test.jsx
> +        useLoaderData.mockReturnValue(null);
Why does this return null? It seems like that would throw an error

2024-06-26 16:11 UTC, Booksh commented on frontend/src/components/problemOccurenceOverview/ProblemOccurrenceOverviewPage.test.jsx
> +        expect(() => {
The syntax of these expect statements is different from the usual ones, did you make it that way intentionally?

2024-06-26 16:20 UTC, Booksh commented on frontend/src/components/problemOccurenceOverview/ProblemOccurrenceOverviewPage.test.jsx
> +    it('alerts unauthorized when API returns 401', async () => {
You could reuse the apiSpy from the previous suite if you put that outside of the describe() function, but it's not very necessary haha, just prettier :)

2024-06-26 16:22 UTC, Booksh commented on frontend/src/components/problemOccurenceOverview/contents/ProblemOccurrenceProblemInstanceList.test.jsx
> +describe('Problem occurrence overview description', () => {
Should probably be ProblemOccurrenceProblemInstanceList or something

2024-06-26 16:35 UTC, Booksh commented on frontend/src/components/problemOccurenceOverview/contents/ProblemOccurrenceSubmission.test.jsx
> +    it('succesfull render with example', async () => {
If possible, would change this into ...with example submission/without example submission, that's a bit clearer

2024-06-26 16:37 UTC, Booksh commented on frontend/src/components/problemOccurenceOverview/contents/ProblemOccurrenceSubmission.test.jsx
Is it easy to add a testcase for whether the example submission actually redirects to/contains the link?

2024-06-26 16:40 UTC, Booksh requested changes
I left some comments, mostly small notation comments.

2024-06-27 07:26 UTC, Doodshoofdaapje commented on frontend/src/components/problemOccurenceOverview/ProblemOccurrenceOverviewPage.test.jsx
> +    it('alerts unauthorized when API returns 401', async () => {
I opted not to do it this time because some give rejected values and some resolved and it would probably worsen readability

2024-06-27 07:28 UTC, Doodshoofdaapje commented on frontend/src/components/problemOccurenceOverview/contents/ProblemOccurrenceProblemInstanceList.test.jsx
> +        // Simulate changing the select value
This already works different on Thijs' branch, so decided to leave it out for now

2024-06-27 07:30 UTC, Doodshoofdaapje commented on frontend/src/components/problemOccurenceOverview/contents/ProblemOccurrenceSubmission.test.jsx
Ill do contain the links

2024-06-27 08:05 UTC, merged