Seeding
SEP-TU-e-2024/website pull request #41
Opened 2024-05-27 14:20 UTC by ThijsEgberts

Added seeding files
Added a guide on how to use and modify the seeding

2024-05-28 09:27 UTC, Doodshoofdaapje requested changes
Tested code and everything seems to be working

2024-05-28 09:27 UTC, Doodshoofdaapje commented on README.md
> +You can also choose to write your own seeder files from scratch with json but that really seems like a hassle.
Would be nice to formalize this slightly instead of saying "in my opinion" and " seems like".

2024-05-28 09:27 UTC, Doodshoofdaapje commented on README.md
> +NOTE: this is not yet a very streamlined workflow so if you find out stuff doesn't work or if you find a better way, please edit the file and send a message in the discord.
Assume most people dont have access to the discord in case this is open sourced

2024-05-28 09:27 UTC, Doodshoofdaapje commented on backend/api/fixtures/0001_init_seed.json
> +        "type": "comp"
Preferably write comp out into Competition, this data is used directly in frontend display

2024-05-28 17:22 UTC, ThijsEgberts commented on backend/api/fixtures/0001_init_seed.json
> +        "type": "comp"
yes done

2024-05-29 10:27 UTC, Doodshoofdaapje approved these changes
![20240517_224112](https://github.com/SEP-TU-e-2024/website/assets/97123208/82200ac5-6b3b-4223-affe-c5eb76893d21)

2024-05-29 10:28 UTC, merged