Leaderboard data
SEP-TU-e-2024/website pull request #43
Opened 2024-05-28 08:06 UTC by marnikdenouden

# Backend

- Added leaderboard and leaderboard entry serializer to create a fixed structure for how the data will be send to the front end. They are in a separate folder called data processing to separate them from serializers that are used on data directly from the data base.
- Sorting of the leaderboard is done in the leaderboard data processing, currently just on a hard coded scoring metric, but we can change this to utilize problem data. Simply call sort from least significant to most with optional reverse parameter to rank the entries.
- Added scripts with get requests for the leaderboard and leaderboard entry data, this is a get request since it is meant to retrieve data only and it allows the data to be cached by http protocols.
- Added urls with variables for leaderboard and leaderboard entry. These urls allow the specific data to be requested and linked to on other pages, we could even add a name to the urls to make it easier.

# Frontend
- Update leaderboard front end to utilize the data requests for the leaderboard.
- Add methods for creating rows, column names and column keys based on the entries and problem of the leaderboard object.
- Removed sorting from the leaderboard table, as the frontend should expect the backend to give a sorted list of entries.

2024-05-28 10:23 UTC, Doodshoofdaapje requested changes
Although functionality seems to be there (besides 1 small error), i think the database structure might have to be rethought, because it feels very clunky to parse our data in this manner.

2024-05-28 10:23 UTC, Doodshoofdaapje commented on frontend/src/components/leaderboardPage/LeaderboardPage.jsx
> +}
If the function is only used once, its fine to hard code it instead. The leaderboard structure will be static anyway and this adds complexity

2024-05-28 10:23 UTC, Doodshoofdaapje commented on frontend/src/components/leaderboardPage/LeaderboardPage.jsx
>  }
If the function is only used once, its fine to hard code it instead. The leaderboard structure will be static anyway and this adds complexity

2024-05-28 10:23 UTC, Doodshoofdaapje commented on frontend/src/components/leaderboardPage/LeaderboardPage.jsx
> +    throw new Error("Problem with fetching the requested data from the database.");
In frontend, also alert the user that something went wrong instead of just throwing an error

2024-05-28 21:23 UTC, marnikdenouden commented on frontend/src/components/leaderboardPage/LeaderboardPage.jsx
> +}
The leaderboard structure can depend on what metrics a problem has, for example path length is a column name specific to a specified problem of the TSP category.

2024-05-28 21:23 UTC, marnikdenouden commented on frontend/src/components/leaderboardPage/LeaderboardPage.jsx
>  }
The leaderboard structure can depend on what metrics a problem has, for example path length is a column key specific to a specified problem of the TSP category.

2024-05-29 09:40 UTC, ThijsEgberts commented on frontend/src/App.jsx
> +              return getLeaderboardData(Number(params.problem_id));
I think it's fine to leave it like this in the pr and just integrate it in another branch

2024-05-29 09:42 UTC, ThijsEgberts commented on frontend/src/components/leaderboardPage/LeaderboardPage.jsx
> +}
This is done on the basic-leaderboard branch, again it's fine to leave it like this in my opinion. Mostly the backen api endpoint is the most important

2024-05-29 09:43 UTC, ThijsEgberts commented on frontend/src/components/leaderboardPage/LeaderboardPage.jsx
> +    throw new Error("Problem with fetching the requested data from the database.");
If you throw an error you will be redirected to the error page, but in this case integrating an error where the leaderboard table should be is probably a good idea indeed

2024-05-29 10:09 UTC, ThijsEgberts commented on frontend/src/components/leaderboardPage/LeaderboardPage.jsx
> +  problemId = problemId.toFixed(0)
Make a comment here to explain what this line does

2024-05-29 12:20 UTC, ThijsEgberts requested changes
Overall looks good besides the comments I left.
I also feel like the data combining is a little bit janky but if it works it's ok as I also don't really know the best practice for this

2024-05-29 15:05 UTC, marnikdenouden commented on frontend/src/components/leaderboardPage/LeaderboardPage.jsx
> +  problemId = problemId.toFixed(0)
Done

2024-05-29 15:05 UTC, marnikdenouden commented on frontend/src/components/leaderboardPage/LeaderboardPage.jsx
> +    fields['rank'] = ++rank;
Done

2024-05-29 15:11 UTC, TPGamesNL commented on backend/api/data_processing/leaderboard_entry.py
> +        self.results = json.dumps(results)
Storing the serialized version of the results in the entry class seems a bit odd, can we move it to the serializer class instead, and have that do it? That way we can also remove the need of calling json.loads in the sorting in leaderboard.py

2024-05-29 15:13 UTC, marnikdenouden commented on frontend/src/components/leaderboardPage/LeaderboardPage.jsx
> +    fields['submissionDate'] = entry.submission.created_at;
I think it is fine like this. Doing it in the front end could allow us to make like a column class that has a header/name/title/label and a method to reference the value from an entry; All is to say the decision for what to display and how to display it is a concern of the front end.

2024-05-29 15:28 UTC, marnikdenouden commented on backend/api/data_processing/leaderboard_entry.py
> +        self.results = json.dumps(results)
Fixed, by finding DictField type, which makes a lot more sense. In this field type we can even specified the key value, which in our case needs to match the char type of a metric.

2024-05-29 15:59 UTC, ThijsEgberts commented on frontend/src/components/leaderboardPage/LeaderboardPage.jsx
> +    fields['submissionDate'] = entry.submission.created_at;
I mean it more that this way you don't really get like a full object of a submission row and I think it would be nicer to make that the responsibility of the backend so the frontend can just display those submission objects.

> Doing it in the front end could allow us to make like a column class that has a header/name/title/label and a method to reference the value from an entry;

I don't really get what you mean by this? The way it is now a list of submission objects is mapped to rows in the leaderboard so I feel like it would be a bit convoluted to do these transformations in the frontend when you can just do it in the backend and get it ready to go

2024-05-30 08:21 UTC, ThijsEgberts approved these changes

2024-05-30 08:21 UTC, ThijsEgberts commented on backend/api/data_processing/leaderboard.py
>          # In the future we could extend this to sort on multiple metrics and sometimes reversed depending what problem specifies.
Make this comment a bit clearer that this is for the main scoring metric of the problem and not just any metric.
Also maybe write a comment that the sorting on column is seperate from this sorting

2024-05-30 09:12 UTC, merged